name: Generate IFC Gantt Charts

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**.ifc'
  release:
    types: [created, published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags

      - name: Download existing Pages content
        continue-on-error: true
        run: |
          PAGES_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

          echo "Mirroring existing Pages site from: $PAGES_URL"

          # Mirror the ENTIRE existing Pages site to preserve other content
          # -m: mirror mode (recursive with timestamping)
          # -np: no parent (don't ascend to parent directory)
          # -nH: no host directories
          # -P _site: save to _site directory
          # --cut-dirs=1: remove first directory component (repo name)
          # -e robots=off: ignore robots.txt
          wget -m -np -nH -P _site --cut-dirs=1 \
            -e robots=off \
            "$PAGES_URL/" 2>&1 | grep -E "(URL:|Downloaded|saved)" || true

          # Remove only the ifc4d top-level index.html (we'll regenerate it)
          rm -f _site/ifc4d/index.html
          echo "Removed ifc4d/index.html (will be regenerated)"

          echo ""
          echo "Existing Pages content:"
          ls -la _site/ 2>/dev/null || echo "No existing content"

          echo ""
          echo "Mirrored ifc4d content:"
          if [ -d "_site/ifc4d/commits" ]; then
            echo "Commits:"
            for commit_dir in _site/ifc4d/commits/*/; do
              if [ -d "$commit_dir" ]; then
                commit=$(basename "$commit_dir")
                file_count=$(find "$commit_dir" -name "*.html" -type f | wc -l)
                echo "  $commit: $file_count files"
              fi
            done
          fi
          if [ -d "_site/ifc4d/tags" ]; then
            echo "Tags:"
            for tag_dir in _site/ifc4d/tags/*/; do
              if [ -d "$tag_dir" ]; then
                tag=$(basename "$tag_dir")
                file_count=$(find "$tag_dir" -name "*.html" -type f | wc -l)
                echo "  $tag: $file_count files"
              fi
            done
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ifc4d-gantt
        run: |
          pip install ifcopenshell
          pip install --no-deps https://github.com/brunopostle/ifc4d-gantt/releases/download/v0.1.0/ifc4d_gantt-0.1.0-py3-none-any.whl

      - name: Find IFC files and generate Gantt charts
        run: |
          mkdir -p _site/ifc4d

          # Get commit SHA (short form)
          COMMIT_SHA=$(git rev-parse --short HEAD)

          # Get tag if this is a tagged commit
          TAG_NAME=$(git describe --exact-match --tags 2>/dev/null || echo "")

          # Create output directory structure
          if [ -n "$TAG_NAME" ]; then
            OUTPUT_DIR="_site/ifc4d/tags/$TAG_NAME"
            LABEL="tag $TAG_NAME"
            VERSION_TYPE="tag"
            VERSION_ID="$TAG_NAME"
          else
            OUTPUT_DIR="_site/ifc4d/commits/$COMMIT_SHA"
            LABEL="commit $COMMIT_SHA"
            VERSION_TYPE="commit"
            VERSION_ID="$COMMIT_SHA"
          fi

          mkdir -p "$OUTPUT_DIR"

          # Find all IFC files and generate charts
          echo "Generating Gantt charts for $LABEL..."
          IFC_COUNT=0

          find . -name "*.ifc" -type f -not -path "./.git/*" | while read -r ifc_file; do
            # Get relative path and create a safe filename
            rel_path="${ifc_file#./}"
            safe_name=$(echo "$rel_path" | sed 's/[^a-zA-Z0-9._-]/_/g')
            output_file="$OUTPUT_DIR/${safe_name%.ifc}.html"

            echo "Processing: $ifc_file -> $output_file"
            ifc4d-gantt "$ifc_file" "$output_file"

            IFC_COUNT=$((IFC_COUNT + 1))
          done

          # Generate index.html for this version
          cat > "$OUTPUT_DIR/index.html" <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8"/>
            <title>IFC Gantt Charts - $LABEL</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
                margin: 40px auto;
                max-width: 800px;
                line-height: 1.6;
                color: #333;
              }
              h1 { color: #24292f; border-bottom: 1px solid #d0d7de; padding-bottom: 8px; }
              h2 { color: #24292f; margin-top: 24px; }
              ul { list-style-type: none; padding: 0; }
              li { margin: 8px 0; padding: 8px; background: #f6f8fa; border-radius: 6px; }
              a { color: #0969da; text-decoration: none; }
              a:hover { text-decoration: underline; }
              .info { color: #57606a; font-size: 0.9em; margin-bottom: 24px; }
              .back-link { margin-bottom: 16px; }
            </style>
          </head>
          <body>
            <div class="back-link"><a href="../../">← All Versions</a></div>
            <h1>IFC Gantt Charts</h1>
            <p class="info">Generated from $LABEL</p>
            <h2>Available Charts:</h2>
            <ul>
          EOF

          # Add links to each generated chart
          find "$OUTPUT_DIR" -name "*.html" ! -name "index.html" -type f | sort | while read -r html_file; do
            filename=$(basename "$html_file")
            # Extract original IFC filename for display
            display_name="${filename%.html}"
            display_name=$(echo "$display_name" | sed 's/_/\//g' | sed 's/\.ifc$//')
            echo "      <li><a href=\"$filename\">$display_name.ifc</a></li>" >> "$OUTPUT_DIR/index.html"
          done

          # Close the index HTML
          cat >> "$OUTPUT_DIR/index.html" <<EOF
            </ul>
          </body>
          </html>
          EOF

          # Get current branch name
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

          # Generate root index.html with actual directory contents
          cat > "_site/ifc4d/index.html" <<INDEX_START
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8"/>
            <title>IFC Gantt Charts - $BRANCH_NAME</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
                margin: 40px auto;
                max-width: 800px;
                line-height: 1.6;
                color: #333;
              }
              h1 { color: #24292f; border-bottom: 1px solid #d0d7de; padding-bottom: 8px; }
              h2 { color: #24292f; margin-top: 24px; }
              ul { list-style-type: none; padding: 0; }
              li { margin: 8px 0; padding: 8px; background: #f6f8fa; border-radius: 6px; }
              a { color: #0969da; text-decoration: none; }
              a:hover { text-decoration: underline; }
              .section { margin-top: 30px; }
              .empty { color: #57606a; font-style: italic; }
            </style>
          </head>
          <body>
            <h1>IFC Gantt Charts - $BRANCH_NAME</h1>

            <div class="back-link"><a href="../">← Main page</a></div>
            <div class="section">
              <h2>Latest Version</h2>
              <ul>
          INDEX_START

          # Add current version with details
          if [ "$VERSION_TYPE" = "tag" ]; then
            tag_msg=$(git tag -l --format='%(contents:subject)' "$VERSION_ID" 2>/dev/null || echo "")
            tag_date=$(git log -1 --format=%ci "$VERSION_ID" 2>/dev/null | cut -d' ' -f1,2 || echo "")
            if [ -n "$tag_msg" ] && [ -n "$tag_date" ]; then
              tag_msg_escaped=$(echo "$tag_msg" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g')
              echo "        <li><a href=\"tags/$VERSION_ID/\"><strong>$VERSION_ID</strong> - $tag_msg_escaped</a><br/><span style=\"color: #57606a; font-size: 0.9em;\">$tag_date</span></li>" >> "_site/ifc4d/index.html"
            else
              echo "        <li><a href=\"tags/$VERSION_ID/\">Tag: $VERSION_ID</a></li>" >> "_site/ifc4d/index.html"
            fi
          else
            commit_msg=$(git log --format=%s -n 1 "$VERSION_ID" 2>/dev/null || echo "")
            commit_date=$(git log --format=%ci -n 1 "$VERSION_ID" 2>/dev/null | cut -d' ' -f1,2 || echo "")
            if [ -n "$commit_msg" ] && [ -n "$commit_date" ]; then
              commit_msg_escaped=$(echo "$commit_msg" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g')
              echo "        <li><a href=\"commits/$VERSION_ID/\"><strong>$VERSION_ID</strong> - $commit_msg_escaped</a><br/><span style=\"color: #57606a; font-size: 0.9em;\">$commit_date</span></li>" >> "_site/ifc4d/index.html"
            else
              echo "        <li><a href=\"commits/$VERSION_ID/\">Commit: $VERSION_ID</a></li>" >> "_site/ifc4d/index.html"
            fi
          fi

          cat >> "_site/ifc4d/index.html" <<'TAGS_START'
              </ul>
            </div>

            <div class="section">
              <h2>All Tags</h2>
              <ul>
          TAGS_START

          # List all tag directories if they exist, with tag messages and dates
          if [ -d "_site/ifc4d/tags" ]; then
            found_tags=false
            for tag_dir in _site/ifc4d/tags/*/; do
              if [ -d "$tag_dir" ]; then
                tag_name=$(basename "$tag_dir")

                # Try to get tag info from git
                tag_msg=$(git tag -l --format='%(contents:subject)' "$tag_name" 2>/dev/null || echo "")
                tag_date=$(git log -1 --format=%ci "$tag_name" 2>/dev/null | cut -d' ' -f1,2 || echo "")

                if [ -n "$tag_msg" ] && [ -n "$tag_date" ]; then
                  tag_msg_escaped=$(echo "$tag_msg" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g')
                  echo "        <li><a href=\"tags/$tag_name/\"><strong>$tag_name</strong> - $tag_msg_escaped</a><br/><span style=\"color: #57606a; font-size: 0.9em;\">$tag_date</span></li>" >> "_site/ifc4d/index.html"
                else
                  echo "        <li><a href=\"tags/$tag_name/\">$tag_name</a></li>" >> "_site/ifc4d/index.html"
                fi
                found_tags=true
              fi
            done
            if [ "$found_tags" = false ]; then
              echo "        <li class=\"empty\">No tags yet</li>" >> "_site/ifc4d/index.html"
            fi
          else
            echo "        <li class=\"empty\">No tags yet</li>" >> "_site/ifc4d/index.html"
          fi

          cat >> "_site/ifc4d/index.html" <<'COMMITS_START'
              </ul>
            </div>

            <div class="section">
              <h2>Recent Commits</h2>
              <ul>
          COMMITS_START

          # List all commit directories if they exist, with commit messages and dates, sorted by date
          if [ -d "_site/ifc4d/commits" ]; then
            # Build a list of commits with their timestamps for sorting
            > /tmp/commits_list.txt
            for commit_dir in _site/ifc4d/commits/*/; do
              if [ -d "$commit_dir" ]; then
                commit_sha=$(basename "$commit_dir")
                # Get timestamp for sorting (epoch time)
                commit_timestamp=$(git log --format=%ct -n 1 $commit_sha 2>/dev/null || echo "0")
                echo "$commit_timestamp|$commit_sha" >> /tmp/commits_list.txt
              fi
            done

            # Check if we have any commits
            if [ -s /tmp/commits_list.txt ]; then
              # Sort by timestamp (descending) and output
              sort -t'|' -k1 -rn /tmp/commits_list.txt | while IFS='|' read timestamp commit_sha; do
                # Try to get commit info from git
                commit_msg=$(git log --format=%s -n 1 $commit_sha 2>/dev/null || echo "")
                commit_date=$(git log --format=%ci -n 1 $commit_sha 2>/dev/null | cut -d' ' -f1,2 || echo "")

                if [ -n "$commit_msg" ] && [ -n "$commit_date" ]; then
                  # Escape HTML special characters in commit message
                  commit_msg_escaped=$(echo "$commit_msg" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g')
                  echo "        <li><a href=\"commits/$commit_sha/\"><strong>$commit_sha</strong> - $commit_msg_escaped</a><br/><span style=\"color: #57606a; font-size: 0.9em;\">$commit_date</span></li>" >> "_site/ifc4d/index.html"
                else
                  # Fallback if commit not in current git history
                  echo "        <li><a href=\"commits/$commit_sha/\">$commit_sha</a></li>" >> "_site/ifc4d/index.html"
                fi
              done
            else
              echo "        <li class=\"empty\">No commits yet</li>" >> "_site/ifc4d/index.html"
            fi

            rm -f /tmp/commits_list.txt
          else
            echo "        <li class=\"empty\">No commits yet</li>" >> "_site/ifc4d/index.html"
          fi

          cat >> "_site/ifc4d/index.html" <<'INDEX_END'
              </ul>
            </div>
          </body>
          </html>
          INDEX_END

          echo "Generated Gantt charts in $OUTPUT_DIR"
          ls -la "$OUTPUT_DIR"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
